"""empty message

Revision ID: 034c93941c93
Revises: 
Create Date: 2023-12-10 19:49:00.577809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '034c93941c93'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product_files', 'file',
               existing_type=sa.BLOB(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.drop_column('products', 'url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('url', mysql.VARCHAR(length=255), nullable=True))
    op.alter_column('product_files', 'file',
               existing_type=sa.String(length=255),
               type_=sa.BLOB(),
               existing_nullable=False)
    # ### end Alembic commands ###
